name: Navi Discounts

services:
  kotlin-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: navi_discounts_app
    restart: unless-stopped
    environment:
       - TELEGRAM_BOT_TOKEN=your_token
       - DB_HOST=nd_db
       - DB_PORT=5432
       - DB_NAME=navi_discounts
       - DATASOURCE_USERNAME=postgres
       - DATASOURCE_PASSWORD=postgres
    ports:
      - "8081:8080"
    depends_on:
      nd_db:
        condition: service_healthy
    networks:
      - backend

  nd_db:
    image: postgres:17-alpine
    container_name: navi_discounts_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: navi_discounts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
