spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: Navi Discounts - Dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:discounts}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:root}
  bot:
    token: ${TELEGRAM_BOT_TOKEN:}
    scheduler:
      enabledExeCommand: ${ENABLED_EXE_COMMAND:true}
      timeZone: ${TIME_ZONE:UTC}
      executionTime: ${EXECUTION_TIME:00:00}

---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: Navi Discounts - Prod
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    scheduler:
      enabledExeCommand: ${ENABLED_EXE_COMMAND:false}
      timeZone: ${TIME_ZONE:UTC}
      executionTime: ${EXECUTION_TIME:00:00}